#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint checks..."
# Run lint and exit with error code if it fails
npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed! Fix the errors before committing."
  exit 1
fi

# Run lint-staged as well
npx lint-staged